development:
  paypal_email:  orders_1327286707_biz@yahoo.com
  paypal_secret: foobar
  paypal_cert_id: PEGQ72VYF8KQQ
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

  cmd: _cart
  upload: 1
  currency: USD
  shipping: 10
  lc: US
  rm: 2

test:
  paypal_email: test@example.com
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: testpaypalurl

production:
  paypal_email: foo@example.com
  paypal_secret: supersecret
  paypal_cert_id: KLHZSK326HEDS
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"

