defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: mysql
  socket: /var/run/mysqld/mysqld.sock
  # username: rls_db_usr
  # password: rls_db_pswd

fotoweekly:
  database: db_fotoweekly
  <<: *defaults

gamelist:
  database: db_gamelist
  <<: *defaults

jobolicious:
  database: db_jobolicious
  <<: *defaults

development:
  database: rails_db
  <<: *defaults

test:
  database: rails_dbtest
  <<: *defaults

production:
  database: rails_db_production
  <<: *defaults

